### PR TITLE
Single repo

### PR DESCRIPTION
**Pull request by erikkemperman**
Note: I've had to force remove your latest commit to the master branch to get this PR to auto-merge (I had done the same change in my branch but git got confused because the single_repo branch has multiple roots, due to imported histories).

To see if you like it, please just `git clone https://github.com/powertac/powertac-core -b single_repo`

### CODE REVIEW

**Comment by jecollins** [comment]
How hard will it be to rename powertac-core into powertac-parent? Is it a good idea?

**Comment by jecollins** [comment]
Perhaps I was too hasty. The name of the maven module need not match the name of the directory. The name of the parent module is indeed correct.

**Comment by jecollins** [comment]
Curious: can we now go back to using symbolic version numbers?

**Comment by erikkemperman** [comment]
You mean rename the powertac-core repository, after the restructure? That would be trivial, github will even forward clients pointing to the old one transparently I think.

Not sure what you mean by symbolic version numbers?

**Comment by jecollins** [comment]
By symbolic versions I mean using powertac-server.version for example rather than 1.4.2-SNAPSHOT

**Comment by erikkemperman** [comment]
Right, I see. If my hypothesis of the earlier problem with powertac.version is correct, probably not... 

But most of the modules now have implicit (inherited) versions and maven-release-plugin in the single repo setup does a good job in stripping SNAPSHOT from literal versions and bumping to next dev iteration.

**Comment by jecollins** [comment]
OK, I tried merging it locally, and I am not confident of the result. It builds, but git is complaining about untracked files that are in fact in the clone of the single_repo branch. These include the README.md files and src directories under each of the former modules. How can the src directories be untracked? Would we be better off letting github do the merge, or do I need to add those src dirs? I guess I can try the latter locally and see what happens.

**Comment by jecollins** [comment]
Wait! github says it's merged. Did I just do a push? I don't think so...

**Comment by erikkemperman** [comment]
You will need to clone a fresh copy after the merge, this is expected because the changes upstream from the pov of an existing copy would overwrite untracked (unversioned) material which the client doesn't allow (I'm not sure if it has an option to override that protection).

**Comment by erikkemperman** [comment]
It looks like you merged it on GH from where I'm standing?

**Comment by jecollins** [comment]
I did not intentionally do it on github, but maybe I slipped? I'm not sure any more. In any case, I blew away my local version and re-cloned it, and it seems fine.

**Comment by erikkemperman** [comment]
All right!

**Comment by jecollins** [comment]
Had to delete and re-import the powertac-core projects into STS. I guess I should deploy also, otherwise when others do this they won't see the powertac-parent pom. Or maybe they will, since the relative path should find it. I cannot easily test this because I had already done a local install.

**Comment by erikkemperman** [comment]
You will have lost the .project file(s), that makes sense. I guess you might have moved it out of the way and then back after the fresh clone, if you did that in the same directory. But not sure if STS would've picked up on the fact that the submodules are no longer separate git repositories.

Importing the super-module in STS should be enough though, at least it was with the version I'm using.

Deploying is needed if you want people cloning current master branches of powertac-server or brokers to be able to find powertac-parent 1.4.2-SNAPSHOT without installing powertac-core locally.

**Comment by erikkemperman** [comment]
Actually that last bit is true with it without this single-repo business, so maybe I'm misunderstanding your point?

**Pull request merged**
