### PR TITLE
Broker adapter

### PR DESCRIPTION
**Pull request by pascalwhoop**
- combined both config properties into one
- if ipc-adapter-name is passed with a bean name as parameter, the cooking is started
- switched to CLI as requested

### CODE REVIEW

**Comment by pascalwhoop** [comment]
Hi @jecollins. As requested the update for CLI. I also merged the two so it's easier in the future to let others add beans without the need to edit core.

- [ ] testing R: I don't have any experience whatsoever with R. If this is a quick thing for you, i'd appreciate the check

**Comment by jecollins** [comment]
(1) You moved the call to setMessageAdapter(), but not the comment that was in front of it.
(2) In setMessageAdapter(), you set rawXml to false if there's no message adapter, but you don't check it after the call.

**Comment by jecollins** [comment]
Never mind, I had not looked at all the commits...

**Comment by jecollins** [comment]
Merged into master, not into broker-adapter.

**Comment by pascalwhoop** [comment]
oops my bad, redo for the other branch?

**Comment by jecollins** [comment]
No, it's already merged and pushed. I have not done a thorough test of the R version, still need to do that, but that does not affect the core.

**Pull request closed without merging**
