### PR TITLE
Misc suggestions post structural refactor

### PR DESCRIPTION
**Pull request by erikkemperman**

### CODE REVIEW

**Comment by jecollins** [comment]
At one point, the dependency on powertac-parent seemed necessary, and the relative-path not so much. I'll have to do some more testing later today.

**Comment by erikkemperman** [comment]
I just committed what it seemed I had to change to get things working from a clean `git clone --recursive`... But might be I did more than strictly necessary, or even two counterproductive changes?

**Comment by jecollins** [comment]
I believe the relativePath is incorrect, and in general we have not been using it correctly. See http://maven.apache.org/ref/3.0/maven-model/maven.html.

**Comment by erikkemperman** [comment]
I must admit I still don't fully understand this option, but had read the same page in an earlier attempt to figure this out... As I read it, having it empty is not the same as not having it at all (in which case the default is `../pom.xml`):

> Set the value to an empty string in case you want to disable the feature and always resolve the parent POM from the repositories. 

Which, given that most of our modules had it at empty, was what I assumed we actually wanted it to do?

The only annoying consequence of setting it empty, as far as I can tell, is when you change a master module and need to rebuild children against it, but without deploying anything to the repository. Like server-master, in the old setup.

But in those cases you can just do a local install of the parent immediately before building the children, and it will use that (subject to some time constraint, I think).

**Comment by jecollins** [comment]
You are correct, I had not read the description carefully enough. But that's not the problem I'm having with the git clone --recursive. It seems that the current version in github is not the same as the version in my system when I committed and pushed powertac-core, even though the status said I was up to date. I need to get that fixed before I do anything else.

**Comment by erikkemperman** [comment]
All right, I'll wait until you have that resolved, and then revisit (rebase) my PRs.

**Pull request merged**
