### PR TITLE
Javadox

### PR DESCRIPTION
**Pull request by erikkemperman**
Some minor changes to reduce warnings/errors during `mvn site`, see also [here](https://github.com/powertac/powertac-server/pull/989).

### CODE REVIEW

**Comment by jecollins** [comment]
Nice work! Still need to publish sample-broker javadocs, which also needs to aggregate common.

**Comment by erikkemperman** [comment]
Ah, had not thought about sample-broker docs — i’m not sure where those would be published. I’ll give it some thought.

**Comment by jecollins** [comment]
I've updated the javadoc link for the server on the [powertac-server wiki](https://github.com/powertac/powertac-server/wiki).

**Comment by jecollins** [comment]
Thanks, I failed to notice that. I think it's cleaned up a bit better now.

**Comment by erikkemperman** [comment]
Looks good to me, thanks! I’ll try to come up with a way to throw sample-broker into the CI as well.

**Comment by erikkemperman** [comment]
@jecollins I've pushed a few more commits, and now the CI is also working for sample-broker. The javadocs are published side by side (I've moved the server ones into a separate subdir).

I hope it's all right that I took the liberty of simply pushing these commits straight to master instead of making PRs again. I hope that's allright, I figured we had more or less agreed this would be a reasonable way to proceed with our javadocs -- and also I had to fiddle a bit and it was a lot easier this way.

The wiki links are updated also.

**Pull request merged**
