### PR TITLE
Broker adapter

### PR DESCRIPTION
**Pull request by pascalwhoop**
Added name based IpcAdapter selection

### CODE REVIEW

**Comment by jecollins** [comment]
I'm getting merge conflicts on README, .gitignore, pom.xml. It looks like the README.md and perhaps the .gitignore from broker-adapter got copied over to powertac-core.

**Comment by pascalwhoop** [comment]
How can that be, those files haven't been touched? 🤔

**Comment by pascalwhoop** [comment]
I didn't copy files cross projects but what do the conflicts look like? Otherwise cherry pick the changes of the Java file that's relevant if that's easier

**Comment by jecollins** [comment]
Very strange. Possibly I messed up, but being on the master branch before pulling down the PR. I should probably start over.

**Comment by pascalwhoop** [comment]
I did have some whitespace issues before I got my IDE straight and set it to the project defaults as stated on the wiki. Maybe it has something to do with GitHub ignoring whitespaces and git local not? But then the files should at least show in the commits..
On 2 Mar 2018 6:55 PM, John Collins <notifications@github.com> wrote:I'm getting merge conflicts on README, .gitignore, pom.xml. It looks like the README.md and perhaps the .gitignore from broker-adapter got copied over to powertac-core.

**Pull request merged**
